name: covid
description: Covid application.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  expandable: ^4.1.3
  json_annotation: ^3.0.1

  provider: ^4.0.5+1

  after_init: ^0.1.2
  cupertino_icons: ^0.1.3

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
